/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import com.toedter.calendar.JDateChooser;

import DAO.DanhSachDatPhong_DAO;
import DAO.LichSuChuyenPhong_DAO;
import DAO.Phong_DAO;

/**
 *
 * @author 84837
 */
public class LichSuChuyenPhong_GUI extends javax.swing.JPanel {
	private DefaultTableModel originalModel;
    private JTable tbLichSuChuyenPhong;
	private LichSuChuyenPhong_DAO lichSuChuyenPhongDao = new LichSuChuyenPhong_DAO();
    private Phong_DAO phongDAO = new Phong_DAO();
    /**
     * Creates new form LichSuChuyenPhong_GUI
     */
    public LichSuChuyenPhong_GUI() {
        initComponents();

        updateHeader();
        
        loadDataToTable();
        

        
		// Lưu model ban đầu ngay khi khởi tạo
        originalModel = (DefaultTableModel) tbLichSuChuyenPhong.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleHoaDon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLichSuChuyenPhong = new javax.swing.JTable();
        JDateChooser txtNgayDoi1 = new com.toedter.calendar.JDateChooser();
        JDateChooser txtNgayDoi2 = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleHoaDon.setText("Lịch sử chuyển phòng");

        
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        
        tbLichSuChuyenPhong.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},  // Bắt đầu với dữ liệu rỗng
                new String[] { "Mã chuyển phòng", "Phòng cũ", "Phòng mới", "Lý do", "Ngày chuyển phòng"}
            ) {
                Class<?>[] types = new Class<?>[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;  // Không cho phép chỉnh sửa dữ liệu trong bảng
                }
            });
        tbLichSuChuyenPhong.setRowHeight(40);
            jScrollPane1.setViewportView(tbLichSuChuyenPhong);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(601, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleHoaDon)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
        );
        
        

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateHeader() {
		JTableHeader header = tbLichSuChuyenPhong.getTableHeader();
		header.setFont(new Font("Times new Romans", Font.BOLD, 16));
	}
    
    public void loadDataToTable() {
    	LichSuChuyenPhong_DAO lichSuChuyenPhongDao = new LichSuChuyenPhong_DAO();
        List<Object[]> dsChuyenPhong = lichSuChuyenPhongDao.getAllLichSuChuyenPhong();

        DefaultTableModel tableModel = new DefaultTableModel(
            new Object[][] {},  // Bắt đầu với dữ liệu rỗng
            new String[] { "Mã chuyển phòng", "Phòng cũ", "Phòng mới", "Lý do", "Ngày chuyển phòng" }
        );

        tbLichSuChuyenPhong.setModel(tableModel);
        tableModel.setRowCount(0);

        // Định dạng ngày theo dd/MM/yyyy
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        int count = 1;
        for (Object[] row : dsChuyenPhong) {
            tableModel.addRow(new Object[]{ 
                row[1],
                row[2],  
                row[3],  
                row[4],  
                dateFormat.format(row[5]),
            });
            count++;
        }
        tableModel.fireTableDataChanged();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleHoaDon;
    // End of variables declaration//GEN-END:variables
}
